Repository LizEuan08/Portfolio-3er-parcial.github.io, pull requests merged in 2023-12, with the labels that each got.

#20 Diego
  CSS/work.css
  Services.html
  img/Rectangle27.png
  img/Rectangle28.png
  img/Rectangle29.png
  img/Rectangle30.png
  img/workheroimg.png
  index.html
  work.html
Labels: enhancement

#21 Diego/Work-error
  CSS/work.css
Labels: bug, enhancement

#28 Arreglos Páginas What we do y Contact.
  CSS/Contact.css
  CSS/Services.css
  Contact.html
  Services.html
  index.html
Labels: bug, enhancement, help wanted

#29 Diego/Responsivo
  CSS/Contact.css
  CSS/Home.css
  CSS/Services.css
  CSS/work.css
  Contact.html
  Services.html
  index.html
  work.html
Labels: enhancement

#30 Corrección de los estilos en las páginas what we do y contact
  CSS/Contact.css
  CSS/Services.css
  Contact.html
  Services.html
Labels: bug, enhancement, help wanted

#31 Diego/Correciones
  CSS/Home.css
Labels: enhancement
