Repository LizEuan08/Portfolio-3er-parcial.github.io, pull requests merged in 2023-11, with the labels that each got.

#13 Sección Header
  CSS/Styles.css
  index.html
Labels: enhancement

#16 Seccion hero
  CSS/Styles.css
  img/saly-vector1.png
  index.html
Labels: enhancement

#17 Sección Services, página what we do
  CSS/Home.css
  CSS/Services.css
  Home.html
  Services.html
  img/apps.png
  img/design.png
  img/web.png
Labels: enhancement, help wanted

#18 Cambio de nombre de la página home a index
  Services.html
  index.html
Labels: bug

#19 Update Services.html
  Services.html
Labels: bug
